openapi: 3.0.0
info:
  description: Network admin operation endpoints and objects.
  title: NetworkAdminManagementClient
  version: 2015-06-15
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azsadmin/resource-manager/network/Microsoft.Network.Admin/preview/2015-06-15/Network.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: azsadmin-Network
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  /providers/Microsoft.Network.Admin/locations:
    get:
      description: Returns the list of supported locations
      operationId: OnPremLocations_List
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationsList"
              examples:
                Returns the list of supported locations.:
                  $ref: "#/components/examples/Returns_the_list_of_supported_locati\
                    ons."
      tags:
        - Network
      x-ms-pageable:
        nextLinkName: nextLink
  "/providers/Microsoft.Network.Admin/locations/{location}/operationResults":
    get:
      description: Returns the list of operation results for a location
      operationId: LocationsOperationResults_List
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/LocationParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OperationResultList"
              examples:
                Returns the list of operation results for a location:
                  $ref: "#/components/examples/Returns_the_list_of_operation_result\
                    s_for_a_location"
      tags:
        - Network
      x-ms-pageable:
        nextLinkName: nextLink
  "/providers/Microsoft.Network.Admin/locations/{location}/operations":
    get:
      description: Returns the list of support REST operations.
      operationId: LocationsOperations_List
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/LocationParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OperationList"
              examples:
                Returns the list of support REST operations.:
                  $ref: "#/components/examples/Returns_the_list_of_support_REST_ope\
                    rations."
      tags:
        - Network
      x-ms-pageable:
        nextLinkName: nextLink
  /providers/Microsoft.Network.Admin/operations:
    get:
      description: Returns the list of support REST operations.
      operationId: Operations_List
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OperationList"
              examples:
                Returns the list of support REST operations.:
                  $ref: "#/components/examples/Returns_the_list_of_support_REST_ope\
                    rations."
      tags:
        - Network
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Network.Admin/adminOverview":
    get:
      description: Get an overview of the state of the network resource provider.
      operationId: ResourceProviderState_Get
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get overview of the state of the network resource provider:
              value: fc8456aa-4843-4079-a152-f3497c63aa73
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-06-15
          examples:
            Get overview of the state of the network resource provider:
              value: 2015-06-15
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdminOverview"
              examples:
                Get overview of the state of the network resource provider:
                  $ref: "#/components/examples/Get_overview_of_the_state_of_the_net\
                    work_resource_provider"
      tags:
        - Network
servers:
  - url: https://adminmanagement.local.azurestack.external
components:
  examples:
    Returns_the_list_of_supported_locations.:
      value:
        nextLink: ""
        value: []
    Returns_the_list_of_operation_results_for_a_location:
      value:
        nextLink: ""
        value: []
    Returns_the_list_of_support_REST_operations.:
      value:
        nextLink: ""
        value: []
    Get_overview_of_the_state_of_the_network_resource_provider:
      value:
        id: /subscriptions/fc8456aa-4843-4079-a152-f3497c63aa73/providers/Microsoft.Network.Admin/adminOverview/
        location: ""
        name: ""
        properties:
          backendIpUsage:
            inUseResourceCount: 11
            totalResourceCount: 411
          loadBalancerMuxHealth:
            errorResourceCount: 0
            healthUnknownCount: 0
            healthyResourceCount: 1
            totalResourceCount: 1
            warningResourceCount: 0
          macAddressUsage:
            inUseResourceCount: 2
            totalResourceCount: 3998720
          provisioningState: Succeeded
          publicIpAddressUsage:
            inUseResourceCount: 31
            totalResourceCount: 255
          virtualGatewayHealth:
            errorResourceCount: 0
            healthUnknownCount: 0
            healthyResourceCount: 1
            totalResourceCount: 1
            warningResourceCount: 0
          virtualNetworkHealth:
            errorResourceCount: 0
            healthUnknownCount: 0
            healthyResourceCount: 0
            totalResourceCount: 0
            warningResourceCount: 0
        type: Microsoft.Network.Admin/adminOverview
  parameters:
    ApiVersionParameter:
      description: Client API Version.
      in: query
      name: api-version
      required: true
      schema:
        type: string
        default: 2015-06-15
      examples:
        Returns the list of supported locations.:
          value: 2015-06-15
        Returns the list of operation results for a location:
          value: 2015-06-15
        Returns the list of support REST operations.:
          value: 2015-06-15
    FilterParameter:
      description: OData filter parameter.
      in: query
      name: $filter
      x-ms-parameter-location: method
      schema:
        type: string
    InlineCountParameter:
      description: OData inline count parameter.
      in: query
      name: $inlineCount
      x-ms-parameter-location: method
      schema:
        type: string
    LocationParameter:
      description: Location of the resource.
      in: path
      name: location
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Returns the list of operation results for a location:
          value: westus
        Returns the list of support REST operations.:
          value: westus
    OrderByParameter:
      description: OData orderBy parameter.
      in: query
      name: $orderBy
      x-ms-parameter-location: method
      schema:
        type: string
    ResourceNameParameter:
      description: Name of the resource.
      in: path
      name: resourceName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    SkipParameter:
      description: OData skip parameter.
      in: query
      name: $skip
      x-ms-parameter-location: method
      schema:
        type: string
    SubscriptionIdParameter:
      description: Subscription credentials which uniquely identify Microsoft Azure
        subscription. The subscription ID forms part of the URI for every
        service call.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
    TopParameter:
      description: OData top parameter.
      in: query
      name: $top
      x-ms-parameter-location: method
      schema:
        type: string
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    AdminOverview:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: Admin overview resource object.
      properties:
        properties:
          $ref: "#/components/schemas/AdminOverviewProperties"
    AdminOverviewProperties:
      description: Admin overview properties.
      properties:
        backendIpUsage:
          $ref: "#/components/schemas/AdminOverviewResourceUsage"
        loadBalancerMuxHealth:
          $ref: "#/components/schemas/AdminOverviewResourceHealth"
        macAddressUsage:
          $ref: "#/components/schemas/AdminOverviewResourceUsage"
        provisioningState:
          description: The provisioning state.
          readOnly: true
          type: string
        publicIpAddressUsage:
          $ref: "#/components/schemas/AdminOverviewResourceUsage"
        virtualGatewayHealth:
          $ref: "#/components/schemas/AdminOverviewResourceHealth"
        virtualNetworkHealth:
          $ref: "#/components/schemas/AdminOverviewResourceHealth"
    AdminOverviewResourceHealth:
      description: Resource health information.
      properties:
        errorResourceCount:
          description: Number of resources in the error state.
          format: int64
          readOnly: true
          type: integer
        healthUnknownCount:
          description: Number of resources in an unknown state.
          format: int64
          readOnly: true
          type: integer
        healthyResourceCount:
          description: Number of resources in the success state.
          format: int64
          readOnly: true
          type: integer
        totalResourceCount:
          description: Total number of resources.
          format: int64
          readOnly: true
          type: integer
        warningResourceCount:
          description: Number of resources in the warning state.
          format: int64
          readOnly: true
          type: integer
    AdminOverviewResourceUsage:
      description: Resource usage information.
      properties:
        inUseResourceCount:
          description: Number of resources in use.
          format: int64
          readOnly: true
          type: integer
        totalResourceCount:
          description: Total number of resources.
          format: int64
          readOnly: true
          type: integer
    Display:
      description: Contains the localized display information for this particular operation
        / action.
      properties:
        description:
          description: The localized, friendly description for the operation. The
            description will be displayed to the user. It should be thorough and
            concise for used in both tooltips and detailed views.
          readOnly: true
          type: string
        operation:
          description: The localized, friendly name for the operation. Use the name as it
            will displayed to the user.
          readOnly: true
          type: string
        provider:
          description: The localized friendly form of the resource provider name â€“ it is
            expected to also include the publisher/company responsible. It
            should use Title Casing and begin with "Microsoft" for 1st party
            services. e.g. "Microsoft Monitoring Insights" or "Microsoft
            Compute."
          readOnly: true
          type: string
        resource:
          description: The localized, friendly version of the resource type related to this
            action or operation; the resource type should match the public
            documentation for the resource provider.
          readOnly: true
          type: string
    Location:
      description: Describes the supported Location
      properties:
        name:
          description: The name of the location the operation is being held.
          readOnly: true
          type: string
    LocationsList:
      description: List of Locations
      properties:
        nextLink:
          description: URI to the next page of locations.
          readOnly: true
          type: string
        value:
          description: Array of locations
          items:
            $ref: "#/components/schemas/Location"
          readOnly: true
          type: array
    Operation:
      description: Describes the supported REST operation.
      properties:
        display:
          $ref: "#/components/schemas/Display"
        name:
          description: The name of the operation being performed on this particular object.
            This name should match the name that appears in RBAC or the event
            service.
          readOnly: true
          type: string
    OperationList:
      description: List of Operations
      properties:
        nextLink:
          description: URI to the next page of operations.
          readOnly: true
          type: string
        value:
          description: Array of operations
          items:
            $ref: "#/components/schemas/Operation"
          readOnly: true
          type: array
    OperationResult:
      description: Describes results of a given operation
      properties:
        name:
          description: The name of the operation being performed on this particular object.
          readOnly: true
          type: string
    OperationResultList:
      description: List of Operation Results
      properties:
        nextLink:
          description: URI to the next page of operations.
          readOnly: true
          type: string
        value:
          description: Array of operation results
          items:
            $ref: "#/components/schemas/OperationResult"
          readOnly: true
          type: array
    ProvisionedResource:
      description: Objects which have a provisioning state.
      properties:
        provisioningState:
          description: The provisioning state.
          readOnly: true
          type: string
      type: object
    Resource:
      description: Base Resource Object
      properties:
        id:
          description: URI of the resource.
          readOnly: true
          type: string
        location:
          description: Region location of resource.
          readOnly: true
          type: string
        name:
          description: Name of the resource.
          readOnly: true
          type: string
        tags:
          additionalProperties:
            type: string
          description: List of key value pairs.
          type: object
        type:
          description: Type of resource.
          readOnly: true
          type: string
      type: object
      x-ms-azure-resource: true
    TenantResource:
      description: These resources are utilized by a single tenant.
      properties:
        subscriptionId:
          description: The subscription ID.
          readOnly: true
          type: string
        tenantResourceUri:
          description: The tenant resource URI.
          readOnly: true
          type: string
      type: object
